name: Build Sapphire

on:
  push:
    paths-ignore:
      - "**/*.md"
  pull_request_target:
  workflow_dispatch:

jobs:
  lint:
    name: Check for lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Build Sapphire
        run: yarn package
      - name: Install 7-Zip
        run: choco install 7zip --no-progress -y
      - name: Clean and Compress Artifacts
        run: |
          $zipPath = "release\build\zip\windows-build.zip"
          if (Test-Path $zipPath) {
            Remove-Item $zipPath -Force
          }
          mkdir release\build\zip
          $retryCount = 0
          $maxRetries = 3
          $delay = 5
          while ($retryCount -lt $maxRetries) {
            try {
              & "C:\Program Files\7-Zip\7z.exe" a $zipPath release\build\*
              break
            } catch {
              Write-Output "Failed to compress files. Retrying in $delay seconds..."
              Start-Sleep -Seconds $delay
              $retryCount++
            }
          }
          if ($retryCount -eq $maxRetries) {
            Write-Error "Failed to compress files after $maxRetries attempts."
            exit 1
          }
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: release/build/zip/windows-build.zip

  # Android build is disabled until we can get the keystore to work properly
  # Keys are not being read properly from the secrets store

  #  build-android:
  #    name: Build Android
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: 20
  #          cache: "yarn"
  #      - name: Install Dependencies
  #        run: yarn install
  #      - name: Make gradlew executable
  #        run: chmod +x ./src/android/gradlew
  #      - name: Build Sapphire
  #        env:
  #          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
  #          ANDROID_KEYSTORE_ALIAS_PASS: ${{ secrets.ANDROID_KEYSTORE_ALIAS_PASS }}
  #        run: |
  #          yarn build:renderer
  #          yarn cap sync
  #          yarn cap build android --keystorepath key.jks --androidreleasetype APK --keystorepass "$ANDROID_KEYSTORE_PASS" --keystorealias key0 --keystorealiaspass "$ANDROID_KEYSTORE_ALIAS_PASS"
  #      - name: Move build files
  #        run: |
  #          mkdir -p release/build/android
  #          mv ./src/android/app/build/outputs/apk/release/app-release-signed.apk ./release/build/android/amethyst-v$(node -p "require('./package.json').version").apk
  #      - name: Compress Artifacts
  #        run: |
  #          mkdir -p release/build/zip
  #          zip -r release/build/zip/android-build.zip release/build/android/*
  #      - name: Upload Artifacts
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: android-build
  #          path: release/build/zip/android-build.zip

  # MacOS build is disabled until MacOS isn't such a pain to work with
  # Sideloading is not properly supported on MacOS & the build process is a pain

  #  build-macos:
  #    name: Build MacOS
  #    runs-on: macos-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: 20
  #          cache: "yarn"
  #      - name: Install Dependencies
  #        run: yarn install
  #      - name: Build Sapphire
  #        run: USE_HARD_LINKS=false yarn package
  #      - name: Compress Artifacts
  #        run: |
  #          mkdir -p release/build/zip
  #          zip -r release/build/zip/macos-build.zip release/build/*
  #      - name: Upload Artifacts
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: macos-build
  #          path: release/build/zip/macos-build.zip

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install linux dependencies
        run: |
          sudo apt update
          sudo apt install -y rpm libarchive-tools
          sudo snap install snapcraft --classic
      - name: Install Dependencies
        run: yarn install
      - name: Build sapphire
        run: yarn package
      - name: Compress Artifacts
        run: |
          mkdir -p release/build/zip
          zip -r release/build/zip/linux-build.zip release/build/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: release/build/zip/linux-build.zip

  publish-releases:
    if: ${{ success() }}
    needs: [build-windows, build-linux]
    name: Publish Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install GitHub CLI and jq
        run: sudo apt-get install -y gh jq unzip
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: release/build
      - name: Decompress Artifacts
        run: |
          mkdir -p release/build/extracted
          if [ -f release/build/windows-build.zip ]; then
            unzip release/build/windows-build.zip -d release/build/extracted
          else
            echo "windows-build.zip not found"
          fi
          if [ -f release/build/linux-build.zip ]; then
            unzip release/build/linux-build.zip -d release/build/extracted
          else
            echo "linux-build.zip not found"
          fi
      - name: Display structure of extracted files
        run: ls -R release/build/extracted
      - name: Check File Sizes and Filter Output Files
        run: |
          mkdir -p release/build/output
          for file in $(find release/build/extracted -type f); do
            echo "File: $file"
            ls -lh "$file"
            if [ ! -s "$file" ]; then
              echo "Skipping empty file: $file"
            else
              case "$file" in
                *.exe|*.AppImage|*.deb|*.dmg)
                  cp "$file" release/build/output/
                  ;;
                *)
                  echo "Skipping non-output file: $file"
                  ;;
              esac
            fi
          done
      - name: Create Draft Release
        id: create_release
        run: |
          UNIQUE_TAG="release-$(date +%Y%m%d%H%M%S)"
          echo "UNIQUE_TAG=$UNIQUE_TAG" >> $GITHUB_ENV
          gh release create "$UNIQUE_TAG" --draft --title "Draft Release $UNIQUE_TAG" --notes "This is a draft release."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Output Files
        run: |
          for file in $(find release/build/output -type f); do
            echo "Uploading asset $file"
            gh release upload "$UNIQUE_TAG" "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UNIQUE_TAG: ${{ env.UNIQUE_TAG }}
