name: Build Sapphire

on:
  push:
    paths-ignore:
      - "**/*.md"
  pull_request_target:
  workflow_dispatch:

jobs:
  lint:
    name: Check for lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Build Sapphire
        run: yarn package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            release/build/*.yml
            release/build/*.yaml
            release/build/*.exe*

  # Android build is disabled until we can get the keystore to work properly
  # Keys are not being read properly from the secrets store

  #  build-android:
  #    name: Build Android
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: 20
  #          cache: "yarn"
  #      - name: Install Dependencies
  #        run: yarn install
  #      - name: Make gradlew executable
  #        run: chmod +x ./src/android/gradlew
  #      - name: Build Sapphire
  #        env:
  #          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
  #          ANDROID_KEYSTORE_ALIAS_PASS: ${{ secrets.ANDROID_KEYSTORE_ALIAS_PASS }}
  #        run: |
  #          yarn build:renderer
  #          yarn cap sync
  #          yarn cap build android --keystorepath key.jks --androidreleasetype APK --keystorepass "$ANDROID_KEYSTORE_PASS" --keystorealias key0 --keystorealiaspass "$ANDROID_KEYSTORE_ALIAS_PASS"
  #      - name: Move build files
  #        run: |
  #          mkdir -p release/build/android
  #          mv ./src/android/app/build/outputs/apk/release/app-release-signed.apk ./release/build/android/amethyst-v$(node -p "require('./package.json').version").apk
  #      - name: Upload Artifacts
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: android-build
  #          path: |
  #            release/build/android/*.apk
  #            release/build/android/*.json

  # MacOS build is disabled until MacOS isn't such a pain to work with
  # Sideloading is not properly supported on MacOS & the build process is a pain

  #  build-macos:
  #    name: Build MacOS
  #    runs-on: macos-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: 20
  #          cache: "yarn"
  #      - name: Install Dependencies
  #        run: yarn install
  #      - name: Build Sapphire
  #        run: USE_HARD_LINKS=false yarn package
  #      - name: Upload Artifacts
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: macos-build
  #          path: |
  #            release/build/*.yml
  #            release/build/*.dmg
  #            release/build/*.dmg.*
  #            release/build/*.zip
  #            release/build/*.zip.*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Install linux dependencies
        run: |
          sudo apt update
          sudo apt install -y rpm libarchive-tools
          sudo snap install snapcraft --classic
      - name: Install Dependencies
        run: yarn install
      - name: Build sapphire
        run: yarn package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: |
            release/build/*.yml
            release/build/*.yaml
            release/build/*.AppImage
            release/build/*.rpm
            release/build/*.deb
            release/build/*.pacman
            release/build/*.snap

  publish-releases:
    if: ${{ success() }}
    needs: [build-windows, build-linux]
    name: Publish Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install GitHub CLI and jq
        run: sudo apt-get install -y gh jq
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: release/build
      - name: Display structure of downloaded files
        run: ls -R release/build
      - name: Create Draft Release
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")
          if [ "$TAG" = "no-tag" ]; then
            gh release create "draft-$(date +%Y%m%d%H%M%S)" --draft --title "Draft Release" --notes "This is a draft release." $(find release/build -type f)
          else
            gh release create "$TAG" --title "Release $TAG" --notes "Release notes for $TAG" $(find release/build -type f)
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload New Assets with Unique Names
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")
          if [ "$TAG" != "no-tag" ]; then
            for file in $(find release/build -type f); do
              RANDOM_SUFFIX=$(shuf -i 1000-9999 -n 1)
              BASENAME=$(basename "$file")
              UNIQUE_NAME="${BASENAME%.*}-$RANDOM_SUFFIX.${BASENAME##*.}"
              echo "Uploading asset $file as $UNIQUE_NAME"
              gh release upload "$TAG" "$file" --name "$UNIQUE_NAME"
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
